definitions:
  entities.ErrResp:
    properties:
      errorMessage:
        example: A horrible, terrible, absolutely awful error
        type: string
    type: object
info:
  contact:
    name: TomasCruz
    url: https://github.com/TomasCruz/users
  description: Users service
  license:
    name: MIT
    url: https://mit-license.org/
  title: Users
  version: "1.0"
paths:
  /health:
    get:
      operationId: health
      produces:
      - application/json
      responses:
        "204":
          description: Healthy
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/entities.ErrResp'
      summary: health check
swagger: "2.0"
